### ISSUE TITLE
MemoryFree.h file missing

### ISSUE THREAD

**Issue by atefth** [maniacbug/FreeRTOS#1]
The header MemoryFree.c is missing and the code cannot compile.

**Comment by PQCraft** [comment]
https://github.com/McNeight/MemoryFree
or
https://github.com/maniacbug/MemoryFree

**Comment by atefth** [comment]
@PQCraft dude, I'm glad you could take a look after 6 years but unfortunately I don't remember anything associated with this at all... sorry. :sob: 

I'm gonna go ahead and close this now!
